# utils/gemini_api.py

import google.generativeai as genai

# ✅ Your API key
GENAI_API_KEY = "AIzaSyDnJOYk4IPZdHgkW77gJudqa1Ix530tkJI"
genai.configure(api_key=GENAI_API_KEY)

# Load Gemini Flash model
model = genai.GenerativeModel("gemini-1.5-flash")

def generate_interview_questions(prompt, language='en'):
    try:
        lang_prefix = "Generate 3 job interview questions in Urdu." if language == 'ur' else "Generate 3 job interview questions in English."
        full_prompt = f"{lang_prefix} The job title or resume summary is: {prompt}"

        response = model.generate_content(full_prompt)
        return response.text.strip().split('\n')
    except Exception as e:
        return [f"[Error] Failed to generate questions: {str(e)}"]

def get_feedback(answer, language='en'):
    try:
        lang_prefix = "Give constructive feedback in Urdu." if language == 'ur' else "Give constructive feedback in English."
        prompt = f"{lang_prefix} Here's the candidate's answer: {answer}"

        response = model.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        print(f"[Gemini ERROR] {e}")
        return f"[Error] Failed to generate feedback: {str(e)}"
def generate_questions_with_gemini(job_title, language='en'):
    """Generates interview questions based on a given job title using the Gemini API.

        Args:
            job_title (str): The job title for which to generate interview questions.
            language (str, optional): The language in which to generate the questions. Defaults to 'en' (English).

        Returns:
            list: A list of interview questions generated by the Gemini API.  Returns an empty list if there is an error or no questions are generated.
                Each question is a string.

        Raises:
            google.generativeai.APIError: If there is an error communicating with the Gemini API.
            Exception: If any other error occurs during the question generation process.
        """
    # Your Gemini API logic here
    ...
